<<<<<<< HEAD
# Generated by Django 5.1.1 on 2024-09-08 08:09
=======
# Generated by Django 5.1.1 on 2024-09-07 07:53
>>>>>>> 2cbd38e98bf9e3beb2278a50632a598be398814d

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration', models.PositiveIntegerField()),
            ],
            options={
<<<<<<< HEAD
                'verbose_name_plural': 'movies',
=======
                'verbose_name_plural': 'Movies',
>>>>>>> 2cbd38e98bf9e3beb2278a50632a598be398814d
            },
        ),
    ]
